backend:
  name: github
  repo: liviamper/Livia-Makes-Perfect-Website
  branch: main
  base_url: https://auth.sveltia.app
  app_id: Ov23lii5yOlDXX336xhy

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

site_url: https://liviamperfect.web.app
logo_url: https://liviamperfect.web.app/assets/images/social.png

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    view_url: "https://liviamperfect.web.app/blog/{{id}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Author", name: "author", widget: "string", default: "Livia Team"}
      - {label: "Seo Description", name: "description", widget: "text"}
      - label: "Category"
        name: "tag"
        widget: "select"
        options: ["Insights", "Marketing", "RevOps", "Ads", "Branding"]
        create: true # Allows the user to add new categories in the future
        default: "Insights"
      - {label: "Featured Post", name: "featured", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
